# yaml-language-server: $schema=https://json.schemastore.org/nuejs-site.json

globals: ["@global"]
libs: ["@library"]

view_transitions: true
native_css_nesting: true
inline_css: true
sections: true

title_template: "Usama Rehman Mughal / %s"
og_image: /img/avatar.png
author: Usama Rehman Mughal
favicon: /img/favicon.jpg
description: Business Growth Automation Specialist • $300K+ Client Results • Helping Business Owners Reclaim 20+ Hours Per Week
port: 8083

# OG image for automation specialist
origin: https://usama-automation.com
og: /img/og-automation.jpg

navigation:
  header:
    - Usama Mughal: /
    - Services: /#services
    - Case Studies: /automation-case-studies/
    - Contact: /contact/

  footer:
    - © Usama Mughal: /
    
    - text: "Automation Specialist"
      url: /
      class: footer-tagline

    - image: /img/upwork.svg
      url: https://www.upwork.com/freelancers/~your-upwork-profile
      alt: Upwork Profile - Top Rated Plus
      size: 22 x 22

    - image: /img/linkedin.svg
      url: https://linkedin.com/in/usama-automation
      alt: LinkedIn Profile
      size: 22 x 22

    - image: /img/github.svg
      url: https://github.com/usama-automation
      alt: Automation Projects
      size: 22 x 22

# Automation-specific metadata
specializations:
  - "Business Process Automation"
  - "Lead Generation Systems"
  - "CRM Integration & Workflow"
  - "No-Code/Low-Code Development"
  - "AI-Powered Automation"

service_tiers:
  quick_win:
    name: "Quick Win Automation"
    price: "$2,997"
    timeline: "1-2 weeks"
    roi: "300-500%"
  
  growth_suite:
    name: "Growth Automation Suite"
    price: "$7,497" 
    timeline: "4-6 weeks"
    roi: "400-800%"
    
  enterprise:
    name: "Enterprise Transformation"
    price: "$15,997"
    timeline: "8-12 weeks"
    roi: "500-1000%"

# Client results for homepage metrics
metrics:
  total_earnings: "$300K+"
  success_rate: "100%"
  projects_completed: "35+"
  hours_saved_weekly: "20+"
  avg_roi: "400%"